### ISSUE TITLE
Check broken links.

### ISSUE THREAD

**Issue by GintasS** [pittcsc/Summer2021-Internships#297]
Error: https://www.citadel.com/careers/open-positions/positions-for-students/ on line 16 is unreachable.
Error: https://motorolasolutions.zrapply.com/en-US/Careers/job/Schaumburg-IL/Software-Engineer_R7477?utm_source=PittCSC on line 78 is unreachable.
Error: https://careers.point72.com/CSJobDetail?jobName=2021-cubist-software-engineering-internship-program&jobCode=CSS-0004136 on line 143 is unreachable.
Error: https://waymo.com/joinus/2331718/ on line 211 is unreachable.
Error: https://waymo.com/joinus/2331572/ on line 211 is unreachable.
Error: https://jobs.fidelity.com/ShowJob/Id/967682/Summer-2021-Undergraduate-Technical-Internship/ on line 110 is unreachable.
Error: https://www.hashicorp.com/job/2366164 on line 289 is unreachable.
Error: https://jobs.chrobinson.com/job/eden-prairie/engineering-product-manager-intern-june-2021-start/209/17375359 on line 324 is unreachable.
Error: https://careers.generalmills.com/job/11290990/ on line 74 is unreachable.
Error: https://boards.greenhouse.io/embed/job_app?token=2354915 on line 293 is unreachable.
Error: https://www.optiver.com/na/en/job-opportunities/Campus/all/Chicago/ on line 51 is unreachable.
Error: https://www.toyotaconnected.com/job?gh_jid=4421992002&did=4040990002 on line 127 is unreachable.
Error: https://www.pinterestcareers.com/jobs/software-engineering-intern-palo-alto-california-united-states on line 222 is unreachable.
Error: https://www.splunk.com/en_us/careers/jobs/technical-residency-internship-summer-16138.html on line 166 is unreachable.
Error: https://jobs.intel.com/page/show/search-results#q=2021&t=Jobs&sort=relevancy&layout=table&f:@countryfullname=[United%20States]&f:@employeetype=[Intern%2FStudent] on line 256 is unreachable.
Error: https://careers.transamerica.com/ShowJob/Id/2616602/Technology-Rotational-Internship-(Summer-2021 on line 300 is unreachable.
Error: https://sjobs.brassring.com/TGnewUI/Search/home/HomeWithPreLoad?PageType=JobDetails&partnerid=25239&siteid=5014&jobid=6674182#jobDetails=6674182_5014 on line 164 is unreachable.
Error: https://careers.caci.com/ListJobs?keyword=2021&&Page=1&SortOrder=desc&SortField=AddedOn on line 323 is unreachable.
Error: https://www.gapinc.com/en-us/jobs/33/85/undergrad-summer-internship-software-engineering?src=JB-10340&rx_source=PittCSC on line 180 is unreachable.
Error: https://career.bayer.com/en/job/software-developer-intern-co-op--SF253628 on line 310 is unreachable.
Error: https://cg.sandia.gov/psc/applicant/EMPLOYEE/HRMS/c/HRS_HRAM_FL.HRS_CG_SEARCH_FL.GBL?Page=HRS_APP_SCHJOB_FL&Action=U on line 349 is unreachable.
Error: https://www.hitachiabb-powergrids.com/career/open-jobs?filter-search=2021&filter-country=US&filter-page=1 on line 344 is unreachable.
Error: https://jobszp1.lanl.gov/OA_HTML/OA.jsp?page=/oracle/apps/irc/candidateSelfService/webui/VisVacDispPG&OAHP=IRC_EXT_SITE_VISITOR_APPL&OASF=IRC_VIS_VAC_DISPLAY&akRegionApplicationId=821&transactionid=1759536200&retainAM=N&addBreadCrumb=RP&p_svid=81425&p_spid=3628350 on line 68 is unreachable.
Error: https://www.gohealth.com/careers/apply-now/id/summer-2021-internship-4911648002/?keyword=2021 on line 368 is unreachable.
Error: https://jobs.gsk.com/en-us/jobs/263689?lang=en-us&previousLocale=en-US on line 382 is unreachable.
Error: https://careers.formlabs.com/job/2381971/apply/ on line 363 is unreachable.
Error: https://jobs.nm.org/job/chicago/it-undergraduate-internship-program-summer-2021/27763/17349578 on line 392 is unreachable.
Error: https://careers.petsmart.com/student-interns/jobs?keywords=Software&page=1&sortBy=relevance&categories=Students on line 389 is unreachable.
Error: https://jobs.nm.org/job/chicago/analytics-undergraduate-internship-program-summer-2021/27763/17349575 on line 392 is unreachable.
Error: https://www.xylem.com/en-lt/careers/career-opportunities/intern---firmware-engineer--summer-2021/ on line 391 is unreachable.
Error: https://www.bms.com/ca/en/job-seekers/job-search-results.html?country=united%20states%20of%20america&category=intern/co-op/student/flex&keyword=2021&page=1 on line 400 is unreachable.
Error: https://careers.transamerica.com/ShowJob/Id/2617593/Data-Science-Internship-(Summer-2021 on line 300 is unreachable.
Error: https://www.xylem.com/en-lt/careers/career-opportunities?page=1&pagesize=96&keyword=2021 on line 391 is unreachable.
Error: https://careers.perspecta.com/jobs?keywords=2021&page=1 on line 399 is unreachable.
Error: https://careers.unitedhealthgroup.com/search-jobs?kw=interns&sp=&re=US&jf=20&sf=8 on line 417 is unreachable.
Error: https://aurora.tech/jobs/4910063002?gh_jid=4910063002 on line 442 is unreachable.
Error: https://careers.nintendo.com/job-openings/listing/2000000084.html?src=CWS-10000 on line 475 is unreachable.
Error: https://www.gdit.com/careers/job/fd643998b/2021-technical-internships/ on line 470 is unreachable.
Error: https://careers.bakerhughes.com/global/en/search-results?keywords=2021 on line 490 is unreachable.
Error: https://bairdcareers.com/career-search/?keyword=2021&zip=&distance=20.0&country=United%20States%20of%20America&state=&office=&career_areas=&spage=1 on line 452 is unreachable.
Error: https://perblue.recruiterbox.com/jobs/fk0qyuj/ on line 491 is unreachable.
Error: https://careers.jabil.com/en/jobs/job/j2253113-it-intern-summer-2021/ on line 497 is unreachable.
Error: https://x.company/careers-at-x/4958949002/ on line 519 is unreachable.
Error: https://jobs.lever.co/backerkit/a0dfc2d1-38c0-47db-8ffd-eac5c9b096c8 on line 510 is unreachable.
Error: https://www.exptechinc.com/pages/careers/# on line 506 is unreachable.
Error: https://pearson.jobs/san-antonio-tx/intern-developer/0972374041C94E1B947186616087DCB7/job/ on line 532 is unreachable.
Error: https://pearson.jobs/iowa-city-ia/intern-sre-site-reliability-engineer/6C1B5E88A1344DDE86B2EB38AE060EFC/job/ on line 532 is unreachable.
Error: https://careers.vmware.com/main/jobs?keywords=2021&page=1&sortBy=relevance&location=United%20States&woe=12&stretchUnit=MILES&stretch=50 on line 539 is unreachable.
Error: https://careers.mcafee.com/job/plano/cybersecurity-technical-support-engineer-intern/731/17956783 on line 567 is unreachable.
Error: https://www.chathamfinancial.com/careers/jobs/software-development-internship-2021-2298460 on line 544 is unreachable.
Error: https://www.remitly.com/us/en/careers/2421662?from=engineering&gh_jid=2421662 on line 546 is unreachable.
Error: https://jobs.drivetime.com/jobs?page_size=50&page_number=1&keyword=Internship&sort_by=score&sort_order=DESC on line 579 is unreachable.
Error: https://sjobs.brassring.com/TGnewUI/Search/home/HomeWithPreLoad?partnerid=25053&siteid=5248&PageType=JobDetails&jobid=1445244 on line 588 is unreachable.
Error: https://jackhenry.avature.net/careers/SearchJobs/2021?jobRecordsPerPage=6& on line 585 is unreachable.
Error: https://www.pega.com/about/careers/11657/front-end-developer-summer-intern on line 639 is unreachable.
Error: https://jobs.siemens.com/healthineers/jobs?page=1&keywords=2021&sortBy=relevance&location=United%20States&woe=12&stretchUnit=MILES&stretch=0 on line 654 is unreachable.
Error: https://sjobs.brassring.com/TGnewUI/Search/home/HomeWithPreLoad?partnerid=25091&siteid=5105&PageType=JobDetails&jobid=702696 on line 644 is unreachable.
Error: https://www.linkup.com/search/results/Summer-2021-jobs?pageNum=1 on line 669 is unreachable.
Error: https://www.playstation.com/en-us/corporate/about/careers/internships/ on line 151 is unreachable.
Error: https://github.com/hjs2000cn on line 688 is unreachable.
Error: https://www.onemedical.com/careers/all-departments/2532004/ on line 646 is unreachable.
Error: https://jobs.cisco.com/jobs/ProjectDetail/Site-Reliability-Engineer-Summer-2021-Internship-Bachelors-Meraki/1301278?source=Cisco+Jobs+Career+Site&tags=CDC+Browse+all+jobs+careers on line 17 is unreachable.
Error: https://jobs.cisco.com/jobs/ProjectDetail/Emerging-Network-Support-Engineer-Intern-Helpdesk-IT-Computer-Science-Summer-2021-Internship-Meraki/1298811?source=Cisco+Jobs+Career+Site&tags=CDC+Browse+all+jobs+careers on line 17 is unreachable.
Error: https://sjobs.brassring.com/TGnewUI/Search/home/HomeWithPreLoad?partnerid=26513&siteid=5661&PageType=JobDetails&jobid=644341 on line 675 is unreachable.
Error: https://jobs.bmoharris.com/us/en/search-results?keywords=2021 on line 612 is unreachable.
Error: https://sjobs.brassring.com/TGnewUI/Search/home/HomeWithPreLoad?partnerid=26513&siteid=5661&PageType=JobDetails&jobid=643956#jobDetails=643956_5661 on line 675 is unreachable.
Error: https://sjobs.brassring.com/TGnewUI/Search/home/HomeWithPreLoad?partnerid=26513&siteid=5661&PageType=JobDetails&jobid=643964#jobDetails=643964_5661 on line 675 is unreachable.
Error: https://jobs.jobvite.com/code42/job/oz6vdfw7 on line 244 is unreachable.
Error: https://careers.steelcase.com/external/FolderDetail/Hedberg-IT-Intern-Summer-2021/2896 on line 322 is unreachable.
Error: https://jobs.jobvite.com/careers/siriusxm/job/ojxEdfwr/apply on line 341 is unreachable.
Error: https://jobs.jobvite.com/sofi/job/oLcEdfwy on line 365 is unreachable.
Error: https://jobs.jobvite.com/nrchealth/job/oduidfwW on line 326 is unreachable.
Error: https://jobs.discover.com/job/11209494/2021-business-technology-internship-program-houston-undergraduate-houston-tx/ on line 39 is unreachable.
Error: https://careers.walmart.com/us/jobs/WD298108-summer-2021-tech-internship on line 123 is unreachable.
Error: https://www.spotifyjobs.com/job/full-stack-engineer-summer-internship/ on line 237 is unreachable.
Error: https://careers.united.com/job/11700503/intern-digital-technology-summer-2021-chicago-il/ on line 445 is unreachable.
Error: https://careers.qurateretailgroup.com/job/11391695/qvc-it-intern-cyber-security-summer-2021-west-chester-pa/ on line 496 is unreachable.
Error: https://careers.qurateretailgroup.com/job/11391694/qvc-it-intern-software-quality-assurance-summer-2021-west-chester-pa/ on line 496 is unreachable.
Error: https://careers.qurateretailgroup.com/job/11391692/qvc-it-intern-software-engineering-summer-2021-west-chester-pa/ on line 496 is unreachable.
Error: https://mckesson.wd3.myworkdayjobs.com/External_Careers/0/refreshFacet/318c8bb6f553100021d223d9780d30be on line 357 is unreachable.
Error: https://sec.wd3.myworkdayjobs.com/Samsung_Careers on line 173 is unreachable.
Error: https://bb.wd3.myworkdayjobs.com/Student/jobs on line 299 is unreachable.
Error: https://harriscomputer.wd3.myworkdayjobs.com/en-US/1/job/Albany-New-York/Software-Development-Intern_R0009298-4 on line 587 is unreachable.
Error: https://workiva.wd1.myworkdayjobs.com/en-US/careers/job/Scottsdale/Summer-2021---Software-Engineering-Intern_R560?source=PittCSC on line 93 is unreachable.
Error: https://mastercard.wd1.myworkdayjobs.com/CorporateCareers/job/Arlington-Virginia/Software-Development-Engineer-Intern--Summer-2021_R-111347-1/?source=PittCSC on line 134 is unreachable.
Error: https://mastercard.wd1.myworkdayjobs.com/CorporateCareers/job/New-York-City-New-York/Software-Development-Engineer-Intern--Summer-2021_R-113651-1/?source=PittCSC on line 134 is unreachable.
Error: https://mastercard.wd1.myworkdayjobs.com/en-US/Campus/job/Arlington-Virginia/Software-Development-Engineer-Intern--Summer-2021-_R-111190?source=PittCSC on line 88 is unreachable.
Error: https://osisoft.wd1.myworkdayjobs.com/en-US/osisoft_careers/job/San-Leandro-California-USA/Software-Developer-Intern---Summer-2021_R002670 on line 155 is unreachable.
Error: https://dell.wd1.myworkdayjobs.com/ExternalNonPublic/2/refreshFacet/318c8bb6f553100021d223d9780d30be on line 137 is unreachable.
Error: https://sonyglobal.wd1.myworkdayjobs.com/en-US/SonyGlobalCareers/job/San-Jose/Intern---Advanced-Computer-Vision---Graphics-Research_JR-102445 on line 142 is unreachable.
Error: https://marvell.wd1.myworkdayjobs.com/en-US/MarvellCareers/job/Santa-Clara-CA/Software-Engineer---Flash-Firmware-Intern_2001010?source=PittCSC on line 141 is unreachable.
Error: https://blackstone.wd1.myworkdayjobs.com/Blackstone_Campus_Careers/job/New-York/XMLNAME-2021-Software-Developer-Summer-Analyst_12259 on line 183 is unreachable.
Error: https://marvell.wd1.myworkdayjobs.com/en-US/MarvellCareers/job/Santa-Clara-CA/Software-Engineer-Intern_2001165 on line 253 is unreachable.
Error: https://stryker.wd1.myworkdayjobs.com/en-US/StrykerCareers/job/Kalamazoo-Michigan/Summer-Internship-2021-Computer-Science--Computer-Engineering--Software-Michigan_R436511-1 on line 153 is unreachable.
Error: https://factset.wd1.myworkdayjobs.com/en-US/FactSetCareers/job/New-York-NY-USA/Software-Engineering-Internship---US-Campus_R7759 on line 132 is unreachable.
Error: https://duckcreek.wd1.myworkdayjobs.com/en-US/duckcreek-linkedin/job/Basking-Ridge-NJ/Software-Engineering-Intern_REQID51798 on line 277 is unreachable.
Error: https://oshkoshcorporation.wd5.myworkdayjobs.com/en-US/Oshkosh/job/Greencastle-Pennsylvania-United-States/Software-Engineering-Internship_R671 on line 276 is unreachable.
Error: https://firstsolar.wd1.myworkdayjobs.com/en-US/FirstSolar/job/Perrysburg-Facility/CLIP-Integration-Intern--Summer-2021-_REQ-007617 on line 553 is unreachable.
Error: https://cubic.wd1.myworkdayjobs.com/en-US/cubic_USA_careers/job/USA-Boston-MA/Software-Engineering-Intern--Boston_REQ_24892 on line 409 is unreachable.
Error: https://athenahealth.wd1.myworkdayjobs.com/External/0/refreshFacet/318c8bb6f553100021d223d9780d30be on line 378 is unreachable.
Error: https://blackbaud.wd1.myworkdayjobs.com/ExternalCareers/0/refreshFacet/318c8bb6f553100021d223d9780d30be on line 564 is unreachable.
Error: https://veritas.wd1.myworkdayjobs.com/careers/0/refreshFacet/318c8bb6f553100021d223d9780d30be on line 514 is unreachable.
Error: https://kla.wd1.myworkdayjobs.com/Search/2/refreshFacet/318c8bb6f553100021d223d9780d30be on line 536 is unreachable.
Error: https://3m.wd1.myworkdayjobs.com/en-US/Search/job/US-Minnesota-Maplewood/Internship---IT-Intern-for-Summer-2021_R01014692 on line 386 is unreachable.
Error: https://statestreet.wd1.myworkdayjobs.com/en-US/Global/job/Burlington-Massachusetts/Summer-2021-Software-Engineering-Internship--Charles-River-Development--Intern_R-651363 on line 589 is unreachable.
Error: https://3m.wd1.myworkdayjobs.com/en-US/Search/job/US-Minnesota-Maplewood/XMLNAME-2021-Undergraduate-Data-Science-Intern_R01020023 on line 386 is unreachable.
Error: https://3m.wd1.myworkdayjobs.com/Search/1/refreshFacet/318c8bb6f553100021d223d9780d30be on line 386 is unreachable.
Error: https://blueorigin.wd5.myworkdayjobs.com/en-US/BlueOrigin/job/Kent-WA/Summer-2021-Internship--Avionics-Software_R5000?mode=job on line 265 is unreachable.
Error: https://commercebank.wd1.myworkdayjobs.com/en-US/CommerceJobs/job/MO---Kansas-City-DowntownPlaza---Kansas-City---KC-Downtown-Trust-Building-922-Walnut-64106/IT-Developer-Intern---Summer-2021_27308 on line 423 is unreachable.
Error: https://andersonsinc.wd1.myworkdayjobs.com/en-US/TheAndersonsCareers/job/Maumee-OH/Intern--Office--IT-Security--Summer-2021-_R6769 on line 424 is unreachable.
Error: https://oshkoshcorporation.wd5.myworkdayjobs.com/en-US/Oshkosh/job/Greencastle-Pennsylvania-United-States/Software-Engineering-Internship_R671 on line 276 is unreachable.
Error: https://ingredion.wd1.myworkdayjobs.com/en-US/IngredionCareers/job/Westchester-IL/Data-Engineer-Intern---Azure--MicroSoft---Summer-2021-_Req-13354 on line 447 is unreachable.
Error: https://amfam.wd1.myworkdayjobs.com/HomesiteCareers on line 651 is unreachable.
Error: https://lytx.wd1.myworkdayjobs.com/en-US/Lytx/job/Office---San-Diego-CA/Embedded-Software-Automation-Engineer-Intern_R-1164 on line 446 is unreachable.
Error: https://inmar.wd1.myworkdayjobs.com/inmarcareers/0/refreshFacet/318c8bb6f553100021d223d9780d30be on line 571 is unreachable.
Error: https://lytx.wd1.myworkdayjobs.com/en-US/Lytx/job/Office---San-Diego-CA/Systems-Data-Engineer-Intern--Summer-2021-_R-1166 on line 446 is unreachable.
Error: https://flir.wd1.myworkdayjobs.com/en-US/flircareers/job/US---Chelmsford-MA/Software-Engineering-Intern_REQ14821-1 on line 566 is unreachable.
Error: https://lytx.wd1.myworkdayjobs.com/en-US/Lytx/job/Office---San-Diego-CA/Machine-Learning-Engineer-Intern--Summer-2021-_R-1165 on line 446 is unreachable.
Error: https://ingredion.wd1.myworkdayjobs.com/IngredionCareers/0/refreshFacet/318c8bb6f553100021d223d9780d30be on line 447 is unreachable.
Error: https://equinix.wd1.myworkdayjobs.com/External/0/refreshFacet/318c8bb6f553100021d223d9780d30be on line 596 is unreachable.
Error: https://ingredion.wd1.myworkdayjobs.com/en-US/IngredionCareers/job/Westchester-IL/Power-BI-Developer-Intern--Summer-2021-_Req-13352 on line 447 is unreachable.
Error: https://boseallaboutme.wd1.myworkdayjobs.com/Bose_Careers/0/refreshFacet/318c8bb6f553100021d223d9780d30be on line 582 is unreachable.
Error: https://lytx.wd1.myworkdayjobs.com/Lytx/0/refreshFacet/318c8bb6f553100021d223d9780d30be on line 446 is unreachable.
Error: https://amfam.wd1.myworkdayjobs.com/Careers/0/refreshFacet/318c8bb6f553100021d223d9780d30be on line 529 is unreachable.
Error: https://jda.wd5.myworkdayjobs.com/en-US/JDA_Careers/job/Dallas/Data-Science-Intern---Luminate-Customer-Success--Summer-2021-_202610-1 on line 384 is unreachable.
Error: https://schnucks.wd5.myworkdayjobs.com/SchnucksCareers/0/refreshFacet/318c8bb6f553100021d223d9780d30be on line 674 is unreachable.
Error: https://jda.wd5.myworkdayjobs.com/en-US/JDA_Careers/job/Scottsdale/Intern--DevOps-Engineering--Summer-2021-_202885-1 on line 384 is unreachable.
Error: https://echo.wd1.myworkdayjobs.com/en-US/Echo_Logistics/job/Chicago-IL/Software-Engineering-Intern---Chicago_R221 on line 620 is unreachable.
Error: https://amfam.wd1.myworkdayjobs.com/en-US/HomesiteCareers/job/MA---Boston/Database-Python-Developer-Intern_R18932-1 on line 651 is unreachable.
Error: https://huntsman.wd1.myworkdayjobs.com/Huntsman/1/refreshFacet/318c8bb6f553100021d223d9780d30be?source=www_huntsman.com_careers_ID on line 666 is unreachable.
Error: https://jda.wd5.myworkdayjobs.com/JDA_Careers/0/refreshFacet/318c8bb6f553100021d223d9780d30be on line 384 is unreachable.
Error: https://amfam.wd1.myworkdayjobs.com/en-US/HomesiteCareers/job/MA---Boston/Data-Scientist-Intern_R19138-2 on line 651 is unreachable.
Error: https://unum.wd1.myworkdayjobs.com/en-US/External/job/USA---TN---Chattanooga/IT-Summer-Internship-2021_816555-1 on line 420 is unreachable.
Error: https://wabtec.wd1.myworkdayjobs.com/wabtec_careers/0/refreshFacet/318c8bb6f553100021d223d9780d30be on line 500 is unreachable.
Error: https://cree.wd5.myworkdayjobs.com/en-US/EXT/job/Durham-NC/Software-Development-Engineer-Intern_20-713 on line 287 is unreachable.
Error: https://mfs.wd1.myworkdayjobs.com/MFS-Careers/0/refreshFacet/318c8bb6f553100021d223d9780d30be on line 387 is unreachable.
Error: https://academy.wd1.myworkdayjobs.com/en-US/Careers/job/Headquarters---Katy-TX/XMLNAME-2021-Summer-Internship_R192716 on line 609 is unreachable.
Error: https://amfam.wd1.myworkdayjobs.com/en-US/HomesiteCareers/job/MA---Boston/Software-Engineer-Intern_R18297-2 on line 651 is unreachable.
Error: https://jda.wd5.myworkdayjobs.com/en-US/JDA_Careers/job/Dallas/Technical-Intern--Summer----Luminate-Customer-Success_202611-1 on line 384 is unreachable.
Error: https://osv-cci.wd1.myworkdayjobs.com/en-US/CCICareers/job/Stamford-CT/Data-Science--Summer-Intern-_2020-2625-1 on line 653 is unreachable.

**Comment by Zmwang622** [comment]
ill look over it!

**Comment by EParmar18** [comment]
I went through and update many, if not all, of the jobs.lever linkes

**Comment by GintasS** [comment]
Thanks!

**Comment by GintasS** [comment]
Removed job.lever links from above, @EParmar18 thanks, but one jobs.lever link is there :D

**Comment by Zmwang622** [comment]
that took a long time lol
