### ISSUE TITLE
More Internships Closed

### ISSUE THREAD

**Issue by Howardma31** [pittcsc/Summer2021-Internships#298]
Here's a list of internships closed, I didn't go through the whole list.
PDT Partners
Jump Trading
RBC
Squarepoint Capital
National Security Agency
BASF
Bank of America
Duolingo Thrive
Capital One
HubSpot
Stripe
MasterCard
Vail Systems
Medtronic
Benchling
Emerson
Tableau
Qumulo
Would be great if I could get a shout out lol

**Comment by EParmar18** [comment]
Just updated them, also added your name on the list. Thanks!
